### ISSUE TITLE
status of  [arnold-longley-2020]

### ISSUE THREAD

**Issue by pfps** [w3c/rch-wg-charter#100]
The explainer document references  [arnold-longley-2020], which sits in the W3C part of the web, and seems to indicate that it is published by W3C but there is no status given for it.  What is the W3C status of this document?

**Comment by pchampin** [comment]
@pfps The [biblio entry](https://w3c.github.io/rch-wg-charter/explainer.html#bib-arnold-longley-2020) has been changed, to no longer imply it was a W3C document. Does that adequately address this issue?

**Comment by pchampin** [comment]
Beyond the domain name "w3.org", the pointer also contains the terms "lists", and "archive", which makes it quite explicit already IMO... However, would you consider it addressed if we replaced "Technical Report" with "Technical Report posted by the authors on a public maliling list"?

**Comment by pfps** [comment]
Lists and archive are explicit for what?  They could easily indicate a member of a list of archived (i.e., long-term) versions of official publications.   Some thought and investigation will determine that this is an attachment to an email message sent to a W3C mailing list, but this is rather more investigation than should be needed.  Looking at the document itself provides no clue as to its status.  Digging through the mailing list archives shows that the document was posted by someone other than the authors of the document.  I can't find anywhere what the actual status of the document is.

**Comment by pchampin** [comment]
Therefore,
> would you consider it addressed if we replaced "Technical Report" with "Technical Report posted by the authors on a public maliling list"?

I meant replacing it *in the biblio entry* of the explainer...

**Comment by pfps** [comment]
It would be much better to get some indication of what the actual status of the document is.  As far as I know the document doesn't even have the status of a Technical Report.  Presumably Digital Bazaar stands behind the document, but that should be stated somewhere easily accessible and Digital Bazaar should say what the status of the document is.   
Independently, it would be better to have some other location of the document, such as arXiv or a W3C member submission.

Reiterating, the document appears to *not* have been posted by the authors.

**Comment by iherman** [comment]
(I am sorry, I may be late to the party...) I believe the cleanest thing would be to publish the report on the Web somewhere and refer to this in the explainer (rather than to the attachment of a mail). This "somewhere" could be Digital Bazaar's site, David's own web site, etc. I do not think that a member submission would be a good avenue: it would take way too much time to do that. 

On W3C space one possible avenue could be the CCG, of course.

**Comment by pchampin** [comment]
> Reiterating, the document appears to not have been posted by the authors.

My bad, I indeed missed that point. 

+1 to what @iherman said, then

**Comment by pchampin** [comment]
@msporny @dlongley would it be possible to host the [arnold-longley-2020] document on a personal website or Digital Bazaar's website?
Also, I realize that we are currently inconsistent in the description of this reference between the charter (which says "W3C Credentials Community Group") and the explainer (which I patched to simply say "Technical Report"). What would the most appropriate description of this document?

**Comment by msporny** [comment]
> @msporny @dlongley would it be possible to host the [arnold-longley-2020] document on a personal website or Digital Bazaar's website?

Yes, this kicked off a big discussion internally. We are trying to publish to arxiv.org now and it turns out the submission process has become involved.

As an aside, we don't see why it can't just be published as a member submission to W3C, but I guess that would require re-formatting the document? Can't we just put it up on W3C somewhere?

**Comment by pchampin** [comment]
>  "Finding the right place" has turned into an ordeal, internally, as we want to put it up somewhere with permanence (and a W3C mailing list is one such location).

I think the issue raised by @pfps boils down to two things:
- the URL is on w3.org, which some people may infer to imply endorsement by W3C,
- the PDF at the other end of this URL does not indicate the status of the document, and in particular does not disconfirm the hint about W3C endorsement.

Here's a proposal:
- instead of pointing directly to the attached PDF, we point to the archived email: https://lists.w3.org/Archives/Public/public-credentials/2021Mar/0220.html
- we label the reference as "Report submitted to the W3C Credentials Community Group mailing list"

@pfps would this address your concern?

**Comment by pfps** [comment]
I'm even more confused now.   The attachment is also (maybe I missed this before) in a list in the draft charter that "will be used as a mathematical underpinning of the work".  So it seems that this document is *going* to be part of the results of the group?

**Comment by pfps** [comment]
I don't know that pointing to the email message helps.   The email issue is from another person (albeit at the same company) and doesn't give an indication of what the status of the document is.  
I suppose that the document is public, as it has been posted to the mailing list of a W3C CG, but is that the intent of the authors and owners of the document?  The other documents have been published, so I know quite a bit about their status, but I don't know as much about this document.
As far as I can tell this document does not provide any new information above what is contained in the other documents.  So, again as far as I can tell, nothing would be lost if this document was not referenced in either the draft charter or the explainer document.

**Comment by pchampin** [comment]
Could we maybe solve this by adding *in this repository*:
- the PDF of the document
- an HTML "card" with the metadata of the document, including
  - the metadata present in the PDF (title, abstract, name and affiliation of the authors)
  - the publication status of the document ("self-published"? "Digital Bazaar technical report" ?)
  - a history of the document (with a link to the email archive where it was first posted, a link to the reviews that were further provided)

Then the two references (in the charter and the explainer, respectively) would point to the HTML card.

@pfps if we go down that path, is there some metadata that should be in the card and that I am forgetting?

**Comment by davidlehn** [comment]
@pfps Just to be clear here:
- What does "status" of a document mean?  What "status" is acceptable, or not, and how is that determined?
- What locations are acceptable, or not, for long term hosting of a document that is linked to?
- Who is acceptable, or not, to put a document somewhere, and how would anyone [even check their identity](https://en.wikipedia.org/wiki/On_the_Internet,_nobody_knows_you%27re_a_dog)?

I understand it's a bit odd to directly link to a mailing list archive attachment.  That leaves out some context.  But also, why does it matter?  It's just a link to a doc.  Take the doc content as it is.  A doc on archive.org, arxiv.org, w3.org, github.io, or any other arbitrary domain ("personal" named ones too) doesn't ensure any provenance, authenticity, or authority of the doc or its contents.  And stepping up to a web of trust and digital signatures and doc hashes seems a bit much when the idea is to simply talk about a doc that you hope hasn't changed since you linked to it.

Practically here, it may be me or @msporny that handles this.  Or maybe @pchampin copying the document.  So the authors still are not directly involved.  That all seems fine to me.  The doc contents stand on their own.  It does seem the bar is set high for this one doc compared to general linking situations.

All that being said, it would be nice to find a better home for that doc.

**Comment by pfps** [comment]
What is status?  Well, has this document actually been released?  It is on a W3C CG mailing list, but put there by someone other than the authors.  
What would be an ideal state?  A W3C member submission would be ideal.  There certainly has been enough time for this to have happened.

**Comment by iherman** [comment]
To be honest, I am a bit at a loss of what we are discussing and why.

The Working Group has several documents that are known to the WG to start with. Three out of those happen to be formal academic publications, the fourth being some sort of working paper produced by some individuals, backed up by some public implementations.

The only important point at this point is that these documents are _**publicly available and have a  stable URI and/or reference**_. I.e., that both the AC and the Working Group members have an unlimited access to the mathematics therein. The only reason the paper of David and Rachel are in a PDF file as part of an attachment to an email at W3C is to ensure its public nature and rely on the commitment of W3C to keep the document unchanged for eternity (as is the case for any mail in its archives). 

I think that is quite all right as is, actually.

I do understand, however, that the sentence

> See also some publications for RDF Dataset Canonicalization that will be used as a mathematical underpinning of the work

may be misunderstood (witnessed by the remark of @pfps: "So it seems that this document is going to be part of the results of the group?"). We may want to consider rewriting this one sentence by 

> See also some publications for RDF Dataset Canonicalization that will serve as inputs for the specification work

(And, actually, there is no reason to put an active link to "RDF Dataset Canonicalization")

For the sake of completeness, we may also want to add the references to Kasten et al. and Carroll et al. to the relevant [explainer section](https://w3c.github.io/rch-wg-charter/explainer.html#generalProblem), too. This should have been done before.

**Comment by pfps** [comment]
If W3C is happy, then I'm happy.

**Comment by pchampin** [comment]
Perfect. Merging #106 and closing then.
