### ISSUE TITLE
Diwala supports W3C LDS WG

### ISSUE THREAD

**Issue by vongohren** [w3c/rch-wg-charter#44]
Diwala would like to add its voice to supporting the creation of the W3C Linked Data Signatures Working Group.

It is crucial work for the requirement for DIDs and Verifiable Credentials, where digital signatures and other proofs over RDF datasets are used for creating/resolving/updating/deactivating DIDs, and for issuing and verifying Verifiable Credentials.

We see LDS as a critical technology in supporting an open trust and assertion ecosystem. We believe that LDS is a key enabling technology to more secure, open, and decentralized networks

We are currently building products that will use this tech going forward!

**Comment by iherman** [comment]
Thanks @vongohren

**Comment by pchampin** [comment]
Dear @vongohren,
the proposed charter has been substantially changed since you submitted your expression of support. More specifically, its scoped has been narrowed down, to address some concerns raised in the Semantic Web community. See also [Ivan Herman's explanation of those changes on the SebWeb mailing list](https://lists.w3.org/Archives/Public/semantic-web/2021Oct/0020.html).

We kindly ask you to review [the new version](https://w3c.github.io/rch-wg-charter/), and either
* renew your expression of interest (by a simple reply to this thread), or
* to close this issue if you do not wish to renew it.

Thanks in advance

**Comment by vongohren** [comment]
@pchampin thanks for the update and if linked data signatures is out I will have to blank. So closing the comment
